# App
spring.application.name=Alpay-Backend
server.port=${PORT:8080}
server.address=0.0.0.0

# Database (override in hosting env vars)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.proc.param_null_passing=true

# Mail (optional for production; set real values in env)
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USER:}
spring.mail.password=${MAIL_PASS:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# Contact receiver
app.contact.to=${CONTACT_TO:osmdigitalweb@gmail.com}

# CORS (comma-separated origin patterns)
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:4200,http://127.0.0.1:4200,http://192.168.*.*:4200,http://10.*.*.*:4200}

# JWT
app.jwt.secret=${JWT_SECRET:QWxwYXktUHJveWVjdG8tSW50ZWdyYWRvcmEtU2VndXJpZGFkLTIwMjYtSFM1Ni1LZXktU3VwZXItU2VjdXJl}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Upload limits
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE:20MB}

#Pagos de planes

PAYMENT_BASIC_MENSUAL_URL=https://buy.stripe.com/test_aFaaEYdsL5DofRu9oZaVa01
PAYMENT_BASIC_ANUAL_URL=https://buy.stripe.com/test_8x29AUgEXe9UfRu7gRaVa00

PAYMENT_PRO_MENSUAL_URL=https://buy.stripe.com/test_pro_month_456
PAYMENT_PRO_ANUAL_URL=https://buy.stripe.com/test_pro_year_456

PAYMENT_EMPRESARIAL_MENSUAL_URL=https://buy.stripe.com/test_business_month_789
PAYMENT_EMPRESARIAL_ANUAL_URL=https://buy.stripe.com/test_business_year_789
