services:
  - type: web
    name: alpay-backend
    env: docker
    plan: starter
    rootDir: sistema-cobranza
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/auth/login
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CONTACT_TO
        sync: false
      - key: CORS_ALLOWED_ORIGIN_PATTERNS
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
